version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: sleep infinity
    pull_policy: always
    volumes:
      - ../..:/workspaces:cached
